apiVersion: apps/v1
kind: Pod
metadata:
  name: spark-customer-data
  namespace: spark-jobs
  labels:
    app: spark-ui
spec:
  initContainers:
  - name: git-sync
    image: registry.k8s.io/git-sync/git-sync:v4.0.0
    volumeMounts:
    - name: git-repo
      mountPath: /tmp/git
    env:
    - name: GITSYNC_REPO
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: repository
    - name: GITSYNC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: git-secret
          key: password
    - name: GITSYNC_PERIOD
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: period
    - name: GITSYNC_REF
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: branch
    - name: GITSYNC_USERNAME
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: username
    - name: GITSYNC_ONE_TIME
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: one-time
    - name: GITSYNC_ROOT
      valueFrom:
        configMapKeyRef:
          name: git-config
          key: root
    - name: GITSYNC_LINK
      value: git-sync
  containers:
    - name: pyspark-driver
      image: registry.example.com:5000/custom-pyspark:latest
      imagePullPolicy: Always
      volumeMounts:
      - name: git-repo
        mountPath: /app
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: git-repo
    emptyDir: {}
